
package autonomousplanner.UI;


import autonomousplanner.ContinuousPath;
import javax.swing.JFileChooser;

/**
 * A save file dialog for saving a path.
 * @author Jared
 */
@SuppressWarnings("serial")
public class SaveFile extends javax.swing.JFrame {
    ContinuousPath bot;
    /**
     * Creates new form SaveFile
     * @param bot
     */
    public SaveFile(ContinuousPath bot) {
        this.bot = bot;
        initComponents();
        this.setLocation(600, 100);
        setTitle("Save a path file...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\notarealfolder"));
        jFileChooser1.setDialogTitle("Open Path");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(evt.getActionCommand().equals(JFileChooser.CANCEL_SELECTION)){
            this.setVisible(false);
        }else{
            bot.savePath(jFileChooser1.getSelectedFile().getAbsoluteFile());
        this.setVisible(false);
        }
        
    }                                             
                                   


    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration                   
}
